#DropClear Configuration File, Enjoy!!

#String(Text, Message) Values You Can Change.
#Change The Output If Player Inputs A Non-Number While Using The /dropclear Command.
NotNumb: That is not a number
#Change The Output If Player Inputs A Negative Value While Using The /dropclear Command.
NegValue: Cant Use Negative Values
#Change The Output If You Try To Use A Radius Higher Than You Are Allow To While Using The /dropclear Command.
TooFar: Too far away
#Change The Output If No Drops Are Found While Using The /dropclear Command.
CantFind: No Drops/Mobs Found
#Change The Output If Player Doesnt Have Permissions To Use The /dropclear Command.
NoPerms:  You don't have permissions to use this
#Change The Output If Drops Are Killed While Using The /dropclear Command.
ItemKill: Items/Mobs Cleared


#Integer(Number) Values You Can Change.
#Change The Max Radius Mods/Non-Ops(No Permissions) Can Use For The /dropclear Command.
Max_Kill_Radius: 10
#Change The Max Radius Admins/Ops(No Permissions) Can Use For The /dropclear Command.
Max_Admin_Kill_Radius: 30